language: perl
perl:
  - 5.10
  - 5.12
  - 5.14
  - 5.16
  - 5.18
  - 5.20
  - 5.22
  - 5.24
  - 5.26
after_success:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - cover -delete
  - perl Build.PL && ./Build build && HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,inc" PERL5LIB="lib" prove t/
  - cover -report coveralls
sudo: false
cache:
  directories:
    - cpan_modules
